# Generated by Django 4.2.2 on 2023-06-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Cantidad', models.IntegerField()),
                ('Genero', models.CharField(max_length=20)),
                ('Artista', models.CharField(max_length=30)),
            ],
        ),
    ]
